name: graphDraw macOS build

on:
  workflow_dispatch:  # Lets you click "Run workflow" in GitHub UI

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.6.1'  # Change to your Qt version
        host: mac
        target: desktop

    - name: Build the app
      run: |
        qmake -makefile graphDraw.pro
        make -j$(sysctl -n hw.ncpu)

    - name: Package as DMG
      run: |
        macdeployqt graphDraw.app -dmg

    - name: Upload DMG artifact
      uses: actions/upload-artifact@v3
      with:
        name: graphDraw
        path: graphDraw.dmg
